### PR TITLE
Use files API on Python 3.9 and later.

### LINKED ISSUE #140: Tests fail on Python 3.11 due to importlib.resources DeprecationWarning
Tests fail on Python 3.11:
```
pep517/in_process/__init__.py:14: in _in_proc_script_path
    return resources.path(__package__, '_in_process.py')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = ('pep517.in_process', '_in_process.py'), kwargs = {}

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
>       warnings.warn(
            f"{func.__name__} is deprecated. Use files() instead. "
            "Refer to https://importlib-resources.readthedocs.io"
            "/en/latest/using.html#migrating-from-legacy for migration advice.",
            DeprecationWarning,
            stacklevel=2,
        )
E       DeprecationWarning: path is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.

/usr/lib64/python3.11/importlib/resources/_legacy.py:18: DeprecationWarning
```

### PR DESCRIPTION
**Pull request by jaraco**
Fixes #140

### CODE REVIEW

**Comment by jaraco** [comment]
I verified the fix by testing it against Setuptools, which encountered #140 in https://github.com/pypa/setuptools/issues/3365#issuecomment-1153413337.

**Comment by jaraco** [comment]
Also, tests pass where they fail without the patch:

```
<user>@bd64ca36c213 / # cd src; tox -e py311
py311 create: /src/.tox/py311
py311 installdeps: -rdev-requirements.txt
py311 installed: attrs==21.4.0,flake8==4.0.1,iniconfig==1.1.1,mccabe==0.6.1,packaging==21.3,pluggy==1.0.0,py==1.11.0,pycodestyle==2.8.0,pyflakes==2.4.0,pyparsing==3.0.9,pytest==7.1.2,pytest-flake8==1.1.1,testpath==0.6.0,tomli==2.0.1
py311 run-test-pre: PYTHONHASHSEED='3028730102'
py311 run-test: commands[0] | pytest
============================================================= test session starts ==============================================================
platform linux -- Python 3.11.0b3, pytest-7.1.2, pluggy-1.0.0
cachedir: .tox/py311/.pytest_cache
rootdir: /src, configfile: pytest.ini
plugins: flake8-1.1.1
collected 70 items                                                                                                                             

doc/conf.py .                                                                                                                            [  1%]
pep517/__init__.py .                                                                                                                     [  2%]
pep517/_compat.py .                                                                                                                      [  4%]
pep517/build.py .                                                                                                                        [  5%]
pep517/check.py .                                                                                                                        [  7%]
pep517/colorlog.py .                                                                                                                     [  8%]
pep517/dirtools.py .                                                                                                                     [ 10%]
pep517/envbuild.py .                                                                                                                     [ 11%]
pep517/meta.py .                                                                                                                         [ 12%]
pep517/wrappers.py .                                                                                                                     [ 14%]
pep517/in_process/__init__.py .                                                                                                          [ 15%]
pep517/in_process/_in_process.py .                                                                                                       [ 17%]
tests/__init__.py .                                                                                                                      [ 18%]
tests/test_build.py ....                                                                                                                 [ 24%]
tests/test_call_hooks.py ...................                                                                                             [ 51%]
tests/test_envbuild.py ...                                                                                                               [ 55%]
tests/test_hook_fallbacks.py .........                                                                                                   [ 68%]
tests/test_inplace_hooks.py .........                                                                                                    [ 81%]
tests/test_meta.py ....                                                                                                                  [ 87%]
tests/samples/buildsys_pkgs/buildsys.py .                                                                                                [ 88%]
tests/samples/buildsys_pkgs/buildsys_minimal.py .                                                                                        [ 90%]
tests/samples/buildsys_pkgs/buildsys_minimal_editable.py .                                                                               [ 91%]
tests/samples/pkg1/pkg1.py .                                                                                                             [ 92%]
tests/samples/pkg2/pkg2.py .                                                                                                             [ 94%]
tests/samples/pkg3/pkg3.py .                                                                                                             [ 95%]
tests/samples/pkg_intree/backend/intree_backend.py .                                                                                     [ 97%]
tests/samples/setup-py/setup.py .                                                                                                        [ 98%]
tests/samples/test-for-issue-104/setup.py .                                                                                              [100%]

============================================================= 70 passed in 14.14s ==============================================================
___________________________________________________________________ summary ____________________________________________________________________
  py311: commands succeeded
  congratulations :)
```

**Comment by jaraco** [comment]
Please let me know if you won't be able to cut a release with this or a similar fix in the next couple of weeks. If not, I'll probably need to suppress these errors or pin to github for the code.

**Comment by jaraco** [comment]
@pfmoore or @takluyver - any feedback on this change? I'd really prefer to get a release of it rather than have a multi-phase suppress/allow across all of my projects.

**Review by pradyunsg — APPROVED** [review]

**Comment by jaraco** [comment]
I've gone ahead and prepared the 0.13 release to get this fix out.

**Pull request merged**
