### PR TITLE
Make zip-safe by relying on importlib.resources

### LINKED ISSUE #6: Wrappers have to be run from a filesystem
Because the `_in_process.py` script is located via `__file__`, the wrappers module won't work from within a zipfile (or other PEP 302 loader). Ideally, that should be fixed (pip runs itself from within a zipfile when run via `get-pip.py`, although it shouldn't be installing anything from source, so it's not clear that it needs PEP 517 support in that scenario).

Just adding this as a reminder for now because I'm not sure what a good solution would be (the wrapper script may be too long to be passed to Python via `-c`).

### PR DESCRIPTION
**Pull request by jaraco**
Fixes #6.

### CODE REVIEW

**Comment by pfmoore** [comment]
I'd prefer the solution to #6 to *not* require an additional dependency. As written, this PR would mean that pip (which vendors pep517) would have to vendor `importlib.resources`, for no actual benefit (pip doesn't need to run `pep517` from a zipfile).

Unless there's a better justification for this change than "fixing #6", I'd prefer not to do this.

**Comment by takluyver** [comment]
As I've probably commented elsewhere, my personal view is that the non-filesystem modules ship sailed: there are plenty of modules which already break in one way or another if they're not loaded from regular files and folders. Too many to ever fix. So I don't feel remotely bad using `__file__` in my code.

**Comment by jaraco** [comment]
I believe `importlib.resources` is the best practice for this. You _could_ also use `pkg_resources.resource_filename`, but that code is deprecated in favor of `importlib.resources`, which is part of stdlib since Python 3.7. So you _wouldn't_ need to vendor anything for Python 3.7 and later and you would only need to vendor `importlib_resources` until you drop support for Python 3.6.

If this were my project, I'd want it not to be tied to the same constraints that `pip` has. I'd prefer for this project to present the best practices and then let pip determine how to best incorporate those practices (perhaps vendoring or patching out undesirable functionality).

**Comment by jaraco** [comment]
Let's not waste any more energy on this issue. I'd rather we spend it on the more important metadata issue.

**Pull request closed without merging**
